"""
AssureX Claim Engine - Utilities
"""

from src.utils.constants import (
    ADJUDICATOR_ROLES,
    PRIVILEGED_ROLES,
    ROLE_ALIASES,
    AuditAction,
    ClaimStatus,
    DecisionType,
    DocumentType,
    NotificationChannel,
    NotificationSeverity,
    NotificationType,
    ProductCategory,
    RoleEnum,
    WarrantyStatus,
    normalize_role,
)
from src.utils.dates import (
    calculate_warranty_expiry,
    days_between,
    format_iso,
    is_warranty_active,
    parse_date,
    parse_datetime,
    today_utc,
    utc_now,
)
from src.utils.file_utils import (
    ALLOWED_EXTENSIONS,
    ALLOWED_MIME_TYPES,
    MAX_FILE_SIZE_BYTES,
    ensure_upload_dir,
    generate_unique_filename,
    sanitize_filename,
    validate_file_extension,
    validate_file_size,
    validate_mime_type,
)
from src.utils.hashing import hash_bytes, hash_file, hash_stream, hash_string

__all__ = [
    "RoleEnum",
    "ClaimStatus",
    "DecisionType",
    "DocumentType",
    "ProductCategory",
    "WarrantyStatus",
    "NotificationType",
    "NotificationChannel",
    "NotificationSeverity",
    "AuditAction",
    "ROLE_ALIASES",
    "PRIVILEGED_ROLES",
    "ADJUDICATOR_ROLES",
    "normalize_role",
    "utc_now",
    "today_utc",
    "parse_date",
    "parse_datetime",
    "format_iso",
    "days_between",
    "calculate_warranty_expiry",
    "is_warranty_active",
    "ALLOWED_EXTENSIONS",
    "ALLOWED_MIME_TYPES",
    "MAX_FILE_SIZE_BYTES",
    "sanitize_filename",
    "generate_unique_filename",
    "validate_file_extension",
    "validate_mime_type",
    "validate_file_size",
    "ensure_upload_dir",
    "hash_bytes",
    "hash_string",
    "hash_file",
    "hash_stream",
]